# config/__init__.py
# 作用：把config标记为python包 + 统一导出常量，让core里的文件能直接导入
from .constants import (
    NASA_TLX_MIN, NASA_TLX_MAX, HRV_DEFAULT,
    SHIP_DEFAULT_LENGTH, SHIP_MAX_RUDDER,
    EXPERIENCE_ADJUST, NIGHT_ADJUST, RUDDER_RESPONSE_COEFF,
    THRUST_SATURATED_COEFF, COMM_DELAY_DEFAULT,
    COGNITIVE_TIME_MIN, COGNITIVE_TIME_MAX,
    OPERATION_TIME_MIN, OPERATION_TIME_MAX
)

# 导出列表，方便外部调用
__all__ = [
    "NASA_TLX_MIN", "NASA_TLX_MAX", "HRV_DEFAULT",
    "SHIP_DEFAULT_LENGTH", "SHIP_MAX_RUDDER",
    "EXPERIENCE_ADJUST", "NIGHT_ADJUST", "RUDDER_RESPONSE_COEFF",
    "THRUST_SATURATED_COEFF", "COMM_DELAY_DEFAULT",
    "COGNITIVE_TIME_MIN", "COGNITIVE_TIME_MAX",
    "OPERATION_TIME_MIN", "OPERATION_TIME_MAX"
]
